# Generated by Django 5.0.1 on 2024-03-22 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contractors", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contractor",
            options={
                "ordering": ["name", "address", "date_create"],
                "verbose_name": "Контрагент",
                "verbose_name_plural": "Контрагенты",
            },
        ),
        migrations.RemoveField(
            model_name="contractor",
            name="time_create",
        ),
        migrations.RemoveField(
            model_name="contractor",
            name="time_update",
        ),
        migrations.AddField(
            model_name="contractor",
            name="date_create",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contractor",
            name="date_update",
            field=models.DateField(auto_now=True, verbose_name="Дата изменения"),
        ),
    ]
