services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - storage/.env
    build:
      context: .
    ports:
      - 8000:8000
    networks:
      - appnet

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - 80:80
    depends_on:
      - django_gunicorn
    networks:
      - appnet

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server
    restart: always
    networks:
      - appnet
    depends_on:
      - django_gunicorn
      - nginx

  celery:
    build:
      context: .
    command: celery -A storage.notification:app worker --loglevel=info
    restart: unless-stopped
    networks:
      - appnet
    depends_on:
      - django_gunicorn
      - nginx
      - redis

networks:
  appnet:
    driver: bridge
    name: appnet

volumes:
  static:

