# Generated by Django 5.0.1 on 2024-03-29 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0006_remove_product_time_create_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "available",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "owned",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "stored",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_name",
                        to="products.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
        ),
    ]
