# Generated by Django 5.0.1 on 2024-04-01 21:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_remove_product_time_create_and_more"),
        ("storage_items", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="storageitem",
            unique_together={("product", "price")},
        ),
    ]
