# Generated by Django 5.0.1 on 2024-04-06 21:05

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("storage_items", "0002_alter_storageitem_unique_together"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="storageitem",
            managers=[
                ("not_zero", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name="storageitem",
            name="owned",
        ),
    ]
