# Generated by Django 5.0.1 on 2024-04-16 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_remove_product_weight"),
        ("storage_items", "0004_storageitem_weight"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="storageitem",
            unique_together={("product", "price", "weight")},
        ),
    ]
