# Generated by Django 5.0.1 on 2024-05-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage_items", "0005_alter_storageitem_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storageitem",
            name="available",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="storageitem",
            name="stored",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
