# Generated by Django 5.0.1 on 2024-05-06 22:03

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_alter_product_note_alter_product_package"),
        ("storage_items", "0006_alter_storageitem_available_alter_storageitem_stored"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="storageitem",
            managers=[
                ("sellable", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="storageitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="storage_items",
                to="products.product",
                verbose_name="Продукт",
            ),
        ),
    ]
