# Generated by Django 5.0.1 on 2024-05-05 08:23

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_items', '0006_alter_storageitem_available_alter_storageitem_stored'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='storageitem',
            managers=[
                ('sellable', django.db.models.manager.Manager()),
            ],
        ),
    ]
