# Generated by Django 5.0.1 on 2024-05-10 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_items', '0007_alter_storageitem_managers'),
        ('storage_items', '0007_alter_storageitem_managers_alter_storageitem_product'),
    ]

    operations = [
    ]
