# Generated by Django 5.0.1 on 2024-03-22 14:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contractors", "0001_initial"),
        ("products", "0005_alter_product_options_alter_product_cutting_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[("Покупка", "Income"), ("Продажа", "Outcome")],
                        default="Продажа",
                        max_length=7,
                    ),
                ),
                ("planned_date", models.DateField(default=datetime.date.today)),
                ("reserved", models.BooleanField(default=False)),
                ("payment", models.BooleanField(default=False)),
                ("executed", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True)),
                ("executed_at", models.DateTimeField(blank=True)),
                ("deleted_at", models.DateTimeField(blank=True)),
                (
                    "contractor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contractors.contractor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Specification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default="0")),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Contract",
                        to="contracts.contract",
                        verbose_name="Контракт",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Product",
                        to="products.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
        ),
    ]
