# Generated by Django 5.0.1 on 2024-03-22 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0002_alter_contract_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contract",
            old_name="planned_date",
            new_name="date_plan",
        ),
        migrations.RenameField(
            model_name="contract",
            old_name="payment",
            new_name="paid",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="executed_at",
        ),
        migrations.AddField(
            model_name="contract",
            name="date_create",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contract",
            name="date_delete",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="date_execution",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="specification",
            name="date_create",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="specification",
            name="date_update",
            field=models.DateField(auto_now=True),
        ),
    ]
