# Generated by Django 5.0.1 on 2024-03-30 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0004_alter_specification_contract"),
        ("products", "0006_remove_product_time_create_and_more"),
        ("storage_items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="specification",
            name="storage_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="storage_item",
                to="storage_items.storageitem",
                verbose_name="Товар со клада",
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Product",
                to="products.product",
                verbose_name="Закупка",
            ),
        ),
    ]
