# Generated by Django 5.0.1 on 2024-04-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0007_specification_variable_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="manager_share",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=7, null=True
            ),
        ),
    ]
