# Generated by Django 5.0.1 on 2024-04-09 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contractors", "0002_alter_contractor_options_and_more"),
        ("contracts", "0009_payments"),
        ("products", "0008_alter_product_cutting_alter_product_producer"),
        ("storage_items", "0003_alter_storageitem_managers_remove_storageitem_owned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="contractor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="contractors.contractor",
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="specifications",
                to="products.product",
                verbose_name="Закупка",
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="storage_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="specifications",
                to="storage_items.storageitem",
                verbose_name="Товар со клада",
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="variable_weight",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
        ),
    ]
