# Generated by Django 5.0.1 on 2024-04-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0010_alter_contract_contractor_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Payments",
            new_name="Payment",
        ),
        migrations.AlterField(
            model_name="contract",
            name="manager_share",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
    ]
