# Generated by Django 5.0.1 on 2024-04-16 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0012_alter_specification_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.TextField(max_length=100)),
                ("date_action", models.DateField(auto_now_add=True)),
                (
                    "contract",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="contracts.contract",
                        verbose_name="Действия",
                    ),
                ),
            ],
        ),
    ]
