# Generated by Django 5.0.1 on 2024-05-03 16:56

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0013_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specification",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=7,
                validators=[
                    contracts.models.decimal_validator,
                    contracts.models.positive_validator,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=10,
                validators=[
                    contracts.models.decimal_validator,
                    contracts.models.positive_validator,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="variable_weight",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=7,
                validators=[
                    contracts.models.decimal_validator,
                    contracts.models.positive_validator,
                ],
            ),
        ),
    ]
