# Generated by Django 5.0.1 on 2024-05-04 22:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contractors", "0002_alter_contractor_options_and_more"),
        ("contracts", "0014_alter_specification_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="contract_type",
            field=models.CharField(
                choices=[("income", "Покупка"), ("outcome", "Продажа")],
                default="outcome",
                max_length=7,
                verbose_name="Тип контракта",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="contractor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="contractors.contractor",
                verbose_name="Контрагент",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="date_plan",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Планируемая дата исполнения"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="note",
            field=models.TextField(blank=True, verbose_name="Заметки"),
        ),
    ]
