# Generated by Django 5.0.1 on 2024-05-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0015_alter_contract_contract_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="Заметки"),
        ),
    ]
