# Generated by Django 5.0.1 on 2024-02-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fish", models.CharField(max_length=50)),
                ("cutting", models.CharField(max_length=5)),
                ("size", models.CharField(blank=True, max_length=15)),
                ("producer", models.TextField(max_length=5)),
                ("package", models.CharField(blank=True, max_length=15)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_update", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
