# Generated by Django 5.0.1 on 2024-02-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
