# Generated by Django 5.0.1 on 2024-02-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="fixed_weight",
            field=models.BooleanField(
                choices=[(0, "взвешенный"), (1, "фиксированный")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="package",
            field=models.CharField(blank=True, default="мешок", max_length=15),
        ),
    ]
