# Generated by Django 5.0.1 on 2024-03-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_product_fixed_weight_alter_product_package"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["fish", "cutting", "size"],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="cutting",
            field=models.CharField(max_length=5, verbose_name="Разделка"),
        ),
        migrations.AlterField(
            model_name="product",
            name="fish",
            field=models.CharField(max_length=50, verbose_name="Название рыбы"),
        ),
        migrations.AlterField(
            model_name="product",
            name="fixed_weight",
            field=models.BooleanField(
                choices=[(0, "переменный"), (1, "фиксированный")],
                default=1,
                verbose_name="Маркировка веса",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="package",
            field=models.CharField(
                blank=True, default="мешок", max_length=15, verbose_name="Упаковка"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="producer",
            field=models.CharField(max_length=50, verbose_name="Производитель"),
        ),
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.CharField(blank=True, max_length=15, verbose_name="Размер"),
        ),
        migrations.AlterField(
            model_name="product",
            name="time_create",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="product",
            name="time_update",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
        ),
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, null=True, verbose_name="Вес"
            ),
        ),
    ]
