# Generated by Django 5.0.1 on 2024-04-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_remove_product_time_create_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Вес",
            ),
        ),
    ]
