# Generated by Django 5.0.1 on 2024-04-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_alter_product_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cutting",
            field=models.CharField(blank=True, max_length=10, verbose_name="Разделка"),
        ),
        migrations.AlterField(
            model_name="product",
            name="producer",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Производитель"
            ),
        ),
    ]
