# Generated by Django 5.0.1 on 2024-04-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_alter_product_cutting_alter_product_producer"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="note",
            field=models.TextField(blank=True),
        ),
    ]
