# Generated by Django 5.0.1 on 2024-04-14 22:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_product_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="fixed_weight",
        ),
    ]
