# Generated by Django 5.0.1 on 2024-04-15 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_remove_product_fixed_weight"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="weight",
        ),
    ]
