# Generated by Django 5.0.1 on 2024-05-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_remove_product_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="note",
            field=models.TextField(blank=True, verbose_name="Заметки"),
        ),
        migrations.AlterField(
            model_name="product",
            name="package",
            field=models.CharField(blank=True, max_length=15, verbose_name="Упаковка"),
        ),
    ]
