# Generated by Django 5.0.1 on 2024-05-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_alter_product_note_alter_product_package"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cutting",
            field=models.CharField(blank=True, max_length=15, verbose_name="Разделка"),
        ),
    ]
